"""empty message

Revision ID: 360b7d5b0bb6
Revises: 1069a3759b65
Create Date: 2019-04-17 19:18:33.711492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '360b7d5b0bb6'
down_revision = '1069a3759b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_tiemstamp', table_name='comments')
    op.drop_column('comments', 'tiemstamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('tiemstamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_comments_tiemstamp', 'comments', ['tiemstamp'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
